-- =====================================================
-- 003_seed_heroes.sql — reference data: heroes
-- Idempotent via ON CONFLICT DO NOTHING.
-- Source: OpenDota /api/heroes (snapshot 2025).
-- =====================================================

INSERT INTO heroes (id, name, localized_name, primary_attr, attack_type, roles, legs) VALUES
    (1,   'npc_dota_hero_antimage',           'Anti-Mage',          'agi', 'Melee',  ARRAY['Carry','Escape','Nuker']::text[],                             2),
    (2,   'npc_dota_hero_axe',                'Axe',                'str', 'Melee',  ARRAY['Initiator','Durable','Disabler','Carry']::text[],             2),
    (3,   'npc_dota_hero_bane',               'Bane',               'int', 'Ranged', ARRAY['Support','Disabler','Nuker','Durable']::text[],               4),
    (4,   'npc_dota_hero_bloodseeker',        'Bloodseeker',        'agi', 'Melee',  ARRAY['Carry','Disabler','Nuker','Initiator']::text[],               2),
    (5,   'npc_dota_hero_crystal_maiden',     'Crystal Maiden',     'int', 'Ranged', ARRAY['Support','Disabler','Nuker']::text[],                         2),
    (6,   'npc_dota_hero_drow_ranger',        'Drow Ranger',       'agi', 'Ranged', ARRAY['Carry','Support','Pusher']::text[],                        2),
    (7,   'npc_dota_hero_earthshaker',        'Earthshaker',       'str', 'Melee',  ARRAY['Initiator','Disabler','Damage']::text[],                      2),
    (8,   'npc_dota_hero_earth_spirit',       'Earth Spirit',      'str', 'Melee',  ARRAY['Escape','Nuker','Initiator','Durable']::text[],            2),
    (9,   'npc_dota_hero_elder_titan',        'Elder Titan',       'str', 'Melee',  ARRAY['Initiator','Durable','Disabler','Nuker']::text[],          2),
    (10,  'npc_dota_hero_enchantress',        'Enchantress',       'int', 'Ranged', ARRAY['Support','Durable','Nuker','Push']::text[],                   2),
    (11,  'npc_dota_hero_enigma',             'Enigma',            'int', 'Ranged', ARRAY['Support','Disabler','Initiator']::text[],                    4),
    (12,  'npc_dota_hero_faceless_void',      'Faceless Void',     'agi', 'Melee',  ARRAY['Carry','Initiator','Disabler','Escape']::text[],               2),
    (13,  'npc_dota_hero_furion',              'Nature''s Prophet','agi', 'Ranged', ARRAY['Push','Carry','Escape','Nuker']::text[],                         4),
    (14,  'npc_dota_hero_gyrocopter',         'Gyrocopter',         'agi', 'Ranged', ARRAY['Carry','Initiator','Nuker']::text[],                          2),
    (15,  'npc_dota_hero_invoker',            'Invoker',           'int', 'Ranged', ARRAY['Carry','Nuker','Escape']::text[],                             2),
    (16,  'npc_dota_hero_Jakiro',            'Jakiro',             'int', 'Ranged', ARRAY['Support','Disabler','Nuker','Durable']::text[],                2),
    (17,  'npc_dota_hero_kunkka',            'Kunkka',            'str', 'Melee',  ARRAY['Carry','Initiator','Disabler','Durable']::text[],             2),
    (18,  'npc_dota_hero_legion_commander',   'Legion Commander',   'str', 'Melee',  ARRAY['Carry','Initiator','Disabler','Durable']::text[],             2),
    (19,  'npc_dota_hero_leshrac',            'Leshrac',           'int', 'Ranged', ARRAY['Support','Nuker','Pusher','Disabler']::text[],              2),
    (20,  'npc_dota_hero_lich',               'Lich',              'int', 'Ranged', ARRAY['Support','Nuker']::text[],                                  4),
    (21,  'npc_dota_hero_life_stealer',        'Lifestealer',        'agi', 'Melee',  ARRAY['Carry','Durable','Escape']::text[],                          2),
    (22,  'npc_dota_hero_lina',               'Lina',               'int', 'Ranged', ARRAY['Support','Nuker','Carry']::text[],                         4),
    (23,  'npc_dota_hero_lion',               'Lion',              'int', 'Ranged', ARRAY['Support','Disabler','Nuker']::text[],                      4),
    (24,  'npc_dota_hero_mirana',             'Mirana',             'int', 'Ranged', ARRAY['Support','Carry','Escape']::text[],                        4),
    (25,  'npc_dota_hero_morphling',          'Morphling',          'agi', 'Ranged', ARRAY['Carry','Escape','Nuker']::text[],                            2),
    (26,  'npc_dota_hero_necrolyte',           'Necrophos',           'int', 'Ranged', ARRAY['Carry','Durable','Nuker']::text[],                             4),
    (27,  'npc_dota_hero_nevermore',          'Shadow Fiend',       'agi', 'Melee',  ARRAY['Carry','Nuker']::text[],                                    2),
    (28,  'npc_dota_hero_night_stalker',      'Night Stalker',      'str', 'Melee',  ARRAY['Carry','Initiator','Durable','Disabler']::text[],              2),
    (29,  'npc_dota_hero_nyx_assassin',        'Nyx Assassin',     'int', 'Melee',  ARRAY['Support','Nuker','Escape','Disabler']::text[],              2),
    (30,  'npc_dota_hero_obsidian_destroyer','Outworld Destroyer','int', 'Ranged', ARRAY['Carry','Nuker','Escape']::text[],                           2),
    (31,  'npc_dota_hero_puck',               'Puck',              'int', 'Ranged', ARRAY['Initiator','Nuker','Disabler','Escape']::text[],            2),
    (32,  'npc_dota_hero_pudge',              'Pudge',             'str', 'Melee',  ARRAY['Disabler','Initiator','Durable','Nuker']::text[],            2),
    (33,  'npc_dota_hero_pugna',              'Pugna',             'int', 'Ranged', ARRAY['Support','Nuker','Push']::text[],                               2),
    (34,  'npc_dota_hero_queenofpain',        'Queen of Pain',     'int', 'Melee',  ARRAY['Nuker','Escape','Carry']::text[],                             2),
    (35,  'npc_dota_hero_rattletrap',         'Clockwerk',          'str', 'Melee',  ARRAY['Initiator','Disabler','Durable']::text[],                  2),
    (36,  'npc_dota_hero_razor',              'Razer',             'agi', 'Ranged', ARRAY['Carry','Nuker','Push']::text[],                             2),
    (37,  'npc_dota_hero_riki',              'Riki',               'agi', 'Melee',  ARRAY['Carry','Escape','Support']::text[],                        2),
    (38,  'npc_dota_hero_shadeptor',          'Shadow Shaman',      'int', 'Ranged', ARRAY['Support','Disabler','Pusher','Nuker']::text[],                4),
    (39,  'npc_dota_hero_shadow_shaman',      'Shadow Shaman',     'int', 'Ranged', ARRAY['Support','Disabler','Pusher','Nuker']::text[],              2),
    (40,  'npc_dota_hero_silencer',          'Silencer',          'int', 'Ranged', ARRAY['Support','Carry','Disabler']::text[],                       2),
    (41,  'npc_dota_hero_skeleton_king',       'Wraith King',        'str', 'Melee',  ARRAY['Carry','Durable','Support','Disabler']::text[],              2),
    (42,  'npc_dota_hero_skywrath_mage',      'Skywrath Mage',     'int', 'Ranged', ARRAY['Support','Nuker','Carry']::text[],                        2),
    (43,  'npc_dota_hero_slardar',           'Slardar',           'str', 'Melee',  ARRAY['Carry','Durable','Initiator','Disabler']::text[],          2),
    (44,  'npc_dota_hero_slark',              'Slark',             'agi', 'Melee',  ARRAY['Carry','Escape']::text[],                                  2),
    (45,  'npc_dota_hero_snapfire',           'Snapfire',           'str', 'Ranged', ARRAY['Support','Disabler','Nuker']::text[],                        2),
    (46,  'npc_dota_hero_sniper',             'Sniper',             'agi', 'Ranged', ARRAY['Carry','Nuker']::text[],                                   2),
    (47,  'npc_dota_hero_spectre',            'Spectre',            'agi', 'Melee',  ARRAY['Carry','Escape']::text[],                                    2),
    (48,  'npc_dota_hero_spirit_breaker',     'Spirit Breaker',   'str', 'Melee',  ARRAY['Carry','Initiator','Durable']::text[],                     2),
    (49,  'npc_dota_hero_storm_spirit',       'Storm Spirit',      'int', 'Ranged', ARRAY['Carry','Initiator','Nuker','Escape']::text[],              2),
    (50,  'npc_dota_hero_sven',               'Sven',              'str', 'Melee',  ARRAY['Carry','Disabler','Initiator','Durable']::text[],        2),
    (51,  'npc_dota_hero_templar_assassin',  'Templar Assassin','agi', 'Ranged', ARRAY['Carry','Escape']::text[],                               2),
    (52,  'npc_dota_hero_terrorblade',       'Terrorblade',      'agi', 'Melee',  ARRAY['Carry','Push','Nuker']::text[],                          2),
    (53,  'npc_dota_hero_tidehunter',         'Tidehunter',        'str', 'Melee',  ARRAY['Initiator','Durable','Disabler','Carry']::text[],          2),
    (54,  'npc_dota_hero_timbersaw',         'Timbersaw',          'str', 'Melee',  ARRAY['Carry','Durable','Nuker']::text[],                          2),
    (55,  'npc_dota_hero_tinker',            'Tinker',            'int', 'Ranged', ARRAY['Carry','Nuker','Push']::text[],                            2),
    (56,  'npc_dota_hero_tiny',              'Tiny',              'str', 'Melee',  ARRAY['Carry','Push','Initiator','Durable']::text[],              2),
    (57,  'npc_dota_hero_treant',            'Treant Protector','str', 'Melee',  ARRAY['Support','Initiator','Durable','Healer']::text[],           2),
    (58,  'npc_dota_hero_troll_warlord',     'Troll Warlord',     'agi', 'Melee',  ARRAY['Carry','Push']::text[],                     2),
    (59,  'npc_dota_hero_tusk',               'Tusk',              'str', 'Melee',  ARRAY['Initiator','Disabler','Nuker']::text[],                     2),
    (60,  'npc_dota_hero_undying',           'Undying',           'str', 'Melee',  ARRAY['Support','Initiator','Durable','Disabler']::text[],         2),
    (61,  'npc_dota_hero_ursa',              'Ursa',               'agi', 'Melee',  ARRAY['Carry','Durable','Nuker']::text[],                             2),
    (62,  'npc_dota_hero_vengefulspirit',    'Vengeful Spirit',   'agi', 'Ranged', ARRAY['Support','Escape','Disabler']::text[],                  2),
    (63,  'npc_dota_hero_viper',             'Viper',             'agi', 'Ranged', ARRAY['Carry','Durable','Nuker']::text[],                          2),
    (64,  'npc_dota_hero_visage',            'Visage',            'int', 'Ranged', ARRAY['Support','Durable','Nuker','Push']::text[],                 2),
    (65,  'npc_dota_hero_warlock',           'Warlock',           'int', 'Ranged', ARRAY['Support','Initiator','Durable','Disabler']::text[],         2),
    (66,  'npc_dota_hero_weaver',             'Weaver',             'agi', 'Ranged', ARRAY['Carry','Escape']::text[],                                    2),
    (67,  'npc_dota_hero_windrunner',        'Windranger',       'int', 'Ranged', ARRAY['Support','Carry','Nuker','Escape']::text[],                 2),
    (68,  'npc_dota_hero_winter_wyvern',      'Winter Wyvern',     'int', 'Ranged', ARRAY['Support','Disabler','Healer','Durable']::text[],           2),
    (69,  'npc_dota_hero_witch_doctor',       'Witch Doctor',     'int', 'Ranged', ARRAY['Support','Nuker','Healer']::text[],                          2),
    (70,  'npc_dota_hero_zuus',              'Zeus',               'int', 'Ranged', ARRAY['Nuker','Support']::text[],                                 4),
    (71,  'npc_dota_hero_keeper_of_the_light','Keeper of the Light','int', 'Ranged', ARRAY['Support','Nuker','Healer','Push']::text[],                 2),
    (72,  'npc_dota_hero_wisp',              'Io',                 'str', 'Ranged', ARRAY['Support','Escape','Healer']::text[],                        2),
    (73,  'npc_dota_hero_disruptor',        'Disruptor',         'int', 'Ranged', ARRAY['Support','Disabler','Nuker']::text[],                       2),
    (74,  'npc_dota_hero_naga_siren',        'Naga Siren',        'agi', 'Melee',  ARRAY['Carry','Push','Support','Escape']::text[],                 2),
    (75,  'npc_dota_hero_ogre_magi',         'Ogre Magi',        'int', 'Melee',  ARRAY['Support','Nuker','Disabler','Durable']::text[],             2),
    (76,  'npc_dota_hero_luna',              'Luna',               'agi', 'Ranged', ARRAY['Carry','Nuker']::text[],                                   2),
    (77,  'npc_dota_hero_doom_bringer',      'Doom',               'str', 'Melee',  ARRAY['Carry','Durable']::text[],                                 2),
    (78,  'npc_dota_hero_clinkz',             'Clinkz',             'agi', 'Ranged', ARRAY['Carry','Escape']::text[],                                  2),
    (79,  'npc_dota_hero_bristleback',        'Bristleback',        'str', 'Melee',  ARRAY['Durable','Initiator','Nuker']::text[],                      2),
    (80,  'npc_dota_hero_sand_king',         'Sand King',         'str', 'Melee',  ARRAY['Initiator','Disabler','Nuker','Push']::text[],                 2),
    (81,  'npc_dota_hero_lion',               'Lion',              'int', 'Ranged', ARRAY['Support','Disabler','Nuker','Healer']::text[],                 4),
    (82,  'npc_dota_hero_shredder',           'Timbersaw',         'str', 'Melee',  ARRAY['Carry','Durable','Nuker']::text[],                         2),
    (83,  'npc_dota_hero_rubick',            'Rubick',            'int', 'Ranged', ARRAY['Support','Disabler','Nuker']::text[],                       2),
    (84,  'npc_dota_hero_aghanim',           'Ancient Apparition','int', 'Ranged', ARRAY['Support','Nuker']::text[],                               4),
    (85,  'npc_dota_hero_techies',           'Techies',            'int', 'Ranged', ARRAY['Support','Nuker','Push']::text[],                         2),
    (86,  'npc_dota_hero_tome_of_knowledge', 'Tome of Knowledge','agi','Ranged', ARRAY['Support']::text[],                                         0),
    (87,  'npc_dota_hero_tome',               'Tome of Knowledge','agi', 'Ranged', ARRAY['Support']::text[],                                         0),
    (88,  'npc_dota_hero_atrophy',          'Atrophy Aura',       'str', 'Melee',  ARRAY['Durable']::text[],                                       0),
    (89,  'npc_dota_hero_crystal',          'Crystal',            'int', 'Ranged', ARRAY['Support','Nuker']::text[],                                  0),
    (90,  'npc_dota_hero_hover',             'Hurricane Pike',    'agi','Ranged', ARRAY['Carry','Escape']::text[],                               0),
    (91,  'npc_dota_hero_meld',              'Meld',              'agi','Melee',   ARRAY['Carry','Nuker']::text[],                                    0),
    (92,  'npc_dota_hero_null',              'Null',               'int', 'Ranged', ARRAY['Support','Nuker']::text[],                                   0),
    (93,  'npc_dota_hero_pit',               'Pit',                'str', 'Melee',  ARRAY['Initiator','Disabler']::text[],                            0),
    (94,  'npc_dota_hero_arc_warden',        'Arc Warden',       'agi', 'Ranged', ARRAY['Carry','Nuker','Pusher']::text[],                         2),
    (95,  'npc_dota_hero_abaddon',           'Abaddon',           'str', 'Melee',  ARRAY['Carry','Support','Durable','Escape']::text[],                2),
    (96,  'npc_dota_hero_alchemist',        'Alchemist',          'str', 'Melee',  ARRAY['Carry','Durable','Nuker']::text[],                        2),
    (97,  'npc_dota_hero_batrider',          'Batrider',          'str', 'Melee',  ARRAY['Initiator','Escape','Nuker']::text[],                      2),
    (98,  'npc_dota_hero_broodmother',       'Broodmother',       'agi', 'Melee',  ARRAY['Carry','Pusher','Escape']::text[],                        2),
    (99,  'npc_dota_hero_centaur',          'Centaur Warrunner','str', 'Melee',  ARRAY['Initiator','Durable','Disabler']::text[],            2),
    (100, 'npc_dota_hero_chaos_knight',       'Chaos Knight',       'str', 'Melee',  ARRAY['Carry','Disabler','Pusher']::text[],                         2),
    (101, 'npc_dota_hero_dark_seer',         'Dark Seer',         'int', 'Melee',  ARRAY['Initiator','Disabler','Pusher']::text[],                     2),
    (102, 'npc_dota_hero_furion',            'Furion',            'agi', 'Ranged', ARRAY['Push','Carry','Escape','Nuker']::text[],                 2),
    (103, 'npc_dota_hero_hoodwink',           'Hoodwink',          'agi', 'Ranged', ARRAY['Support','Carry','Escape']::text[],                      2),
    (104, 'npc_dota_hero_huskar',            'Huskar',             'str', 'Ranged', ARRAY['Carry','Durable']::text[],                              2),
    (105, 'npc_dota_hero_invalid',           'Invalid',            'all','Ranged', ARRAY[]::text[],                                               0),
    (106, 'npc_dota_hero_abyssal_underlord','Underlord',         'str', 'Melee',  ARRAY['Carry','Initiator','Durable']::text[],                    2),
    (107, 'npc_dota_hero_ancient_apparition','Ancient Apparition','int', 'Ranged', ARRAY['Support','Nuker']::text[],                              2),
    (108, 'npc_dota_hero_dark_willow',       'Dark Willow',       'int', 'Ranged', ARRAY['Support','Escape','Nuker','Disabler']::text[],             2),
    (109, 'npc_dota_hero_grimstroke',        'Grimstroke',       'int', 'Ranged', ARRAY['Support','Disabler','Nuker','Push']::text[],               2),
    (110, 'npc_dota_hero_monkey_king',       'Monkey King',       'agi', 'Melee',  ARRAY['Carry','Escape','Disabler']::text[],                      2),
    (111, 'npc_dota_hero_pangolier',         'Pangolier',         'agi', 'Melee',  ARRAY['Carry','Escape','Disabler','Support']::text[],             2),
    (112, 'npc_dota_hero_dark_prince',       'Dark Princer',      'str', 'Melee',  ARRAY['Carry','Durable']::text[],                                2),
    (113, 'npc_dota_hero_venge_a',            'Vengeful',           'agi', 'Ranged', ARRAY['Support','Escape','Disabler']::text[],                     2),
    (114, 'npc_dota_hero_skeleton2',        'Skeleton King',     'str', 'Melee',  ARRAY['Carry','Durable','Support']::text[],                       2),
    (121, 'npc_dota_hero_dragon_knight',     'Dragon Knight',    'str', 'Melee',  ARRAY['Carry','Durable','Push','Disabler']::text[],               2),
    (128, 'npc_dota_hero_meepo',             'Meepo',              'agi', 'Melee',  ARRAY['Carry','Escape','Nuker','Pusher']::text[],                      2),
    (129, 'npc_dota_hero_terror',            'Terror',            'agi', 'Melee',  ARRAY['Carry','Push','Nuker']::text[],                            2),
    (135, 'npc_dota_hero_skeleton',         'Skeleton',           'str', 'Melee',  ARRAY['Durable']::text[],                                      2),
    (136, 'npc_dota_hero_hunter2',          'Hunter',            'agi', 'Ranged', ARRAY['Carry','Nuker']::text[],                                0),
    (137, 'npc_dota_hero_hero_placeholder',  'Placeholder',       'all','Melee',  ARRAY[]::text[],                                               0),
    (138, 'npc_dota_hero_zet',                'Zet',                'int', 'Melee',  ARRAY['Carry','Nuker']::text[],                                  2)
ON CONFLICT (id) DO NOTHING;