# syntax=docker/dockerfile:1.7
FROM od-base-local AS builder
RUN --mount=type=cache,target=/root/.cache/go-build,sharing=locked \
    --mount=type=cache,target=/go/pkg/mod,sharing=locked \
    CGO_ENABLED=0 GOOS=linux go build -o /bin/enricher ./cmd/enricher

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
RUN adduser -D -u 10001 app
WORKDIR /app
COPY --from=builder /bin/enricher /bin/enricher
USER app
ENTRYPOINT ["/bin/enricher"]